package com.dipsscor.app;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import io.swagger.v3.oas.annotations.tags.Tag;

@RestController
@RequestMapping("/api/v1")
@Tag(name = "OpenAI Integration Service", description = "")
public class SpringAIController {

	@Autowired
	AIServiceHelper aiService;

	/**
	 * Handles a question-answer request by providing a response generated by the AI service.
	 *
	 * @param question The question asked by the user.
	 * @return The response generated by the AI service.
	 */
	@GetMapping("/openai-chat")
	public String chat(@RequestParam String question) {
		return aiService.chat(question);
	}

	/**
	 * Generates a document based on the provided topic using the AI service.
	 *
	 * @param topic The topic for which the document needs to be generated.
	 * @return A string representing the generated document.
	 */
	@GetMapping("/openai-document")
	public String generateDocument(@RequestParam String topic) {
		return aiService.generateDocument(topic);
	}

}
